FROM node:16-alpine
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json .
RUN npm install --save axios react-router-dom
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY --chown=node:node . .

CMD ["npm", "run", "start"]