version: "3"
services:
  client:
    mem_limit: 128m
    image: "vivekbhadauria/multi-docker-fib-app-client"
  api:
    mem_limit: 128m
    image: "vivekbhadauria/multi-docker-fib-app-server"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    mem_limit: 128m
    image: "vivekbhadauria/multi-docker-fib-app-worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  proxy:
    mem_limit: 128m
    image: "vivekbhadauria/multi-docker-fib-app-nginx"
    ports:
      - "80:80"
