name: Deploy Multi Container Fibonacci Calculator App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Source Code
      - uses: actions/checkout@v2

      # Docker Hub Login
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Run Project Tests
      - run: docker build -t vivekbhadauria/multi-docker-fib-app-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true vivekbhadauria/multi-docker-fib-app-test npm run test

      # Build Multiple Docker Images Per Service
      - run: docker build -t vivekbhadauria/multi-docker-fib-app-client ./client
      - run: docker build -t vivekbhadauria/multi-docker-fib-app-nginx ./nginx
      - run: docker build -t vivekbhadauria/multi-docker-fib-app-server ./server
      - run: docker build -t vivekbhadauria/multi-docker-fib-app-worker ./worker

      # Push Created Docker Images To Docker Hub 
      - run: docker push vivekbhadauria/multi-docker-fib-app-client
      - run: docker push vivekbhadauria/multi-docker-fib-app-nginx
      - run: docker push vivekbhadauria/multi-docker-fib-app-server
      - run: docker push vivekbhadauria/multi-docker-fib-app-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-049730269576
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip